Repository ita-social-projects/WhatBackend, pull requests merged in 2020-12, with the labels that each got.

#214 Remove Library folder
  CharlieBackend.Library/CharlieBackend.Library.csproj
  CharlieBackend.Library/SwaggerExamples/AccountsController/GetAllAccountResponse.cs
  CharlieBackend.Library/SwaggerExamples/AccountsController/GetAllNotAssignedAccountsResponse.cs
  CharlieBackend.Library/SwaggerExamples/AccountsController/PostAccountRequest.cs
  CharlieBackend.Library/SwaggerExamples/AccountsController/PostAccountResponse.cs
  CharlieBackend.Library/SwaggerExamples/AccountsController/SignInRequest.cs
  CharlieBackend.Library/SwaggerExamples/AccountsController/SignInResponse.cs
  CharlieBackend.Library/SwaggerExamples/CoursesController/GetAllCoursesResponses.cs
  CharlieBackend.Library/SwaggerExamples/CoursesController/PostCourseRequest.cs
  CharlieBackend.Library/SwaggerExamples/CoursesController/PostCourseResponse.cs
  CharlieBackend.Library/SwaggerExamples/ImportController/ImportDataFromFileRequest.cs
  CharlieBackend.Library/SwaggerExamples/ImportController/ImportDataFromFileResponse.cs
  CharlieBackend.Library/SwaggerExamples/LessonsController/AssignMentorToLessonRequest.cs
  CharlieBackend.Library/SwaggerExamples/LessonsController/AssignMentorToLessonResponse.cs
  CharlieBackend.Library/SwaggerExamples/LessonsController/GetAllLessonsResponse.cs
  CharlieBackend.Library/SwaggerExamples/LessonsController/GetStudentLessonsResponse.cs
  CharlieBackend.Library/SwaggerExamples/LessonsController/PostLessonRequest.cs
  CharlieBackend.Library/SwaggerExamples/LessonsController/PostLessonResponse.cs
  CharlieBackend.Library/SwaggerExamples/LessonsController/PutLessonRequest.cs
  CharlieBackend.Library/SwaggerExamples/MentorsController/GetAllMentorsResponse.cs
  CharlieBackend.Library/SwaggerExamples/MentorsController/PostMentorRequest.cs
  CharlieBackend.Library/SwaggerExamples/MentorsController/PutMentorRequest.cs
  CharlieBackend.Library/SwaggerExamples/MentorsController/PutMentorResponse.cs
  CharlieBackend.Library/SwaggerExamples/SecretariesController/GetAllSecretariesResponse.cs
  CharlieBackend.Library/SwaggerExamples/SecretariesController/PostSecretaryRequest.cs
  CharlieBackend.Library/SwaggerExamples/SecretariesController/PutSecretaryRequest.cs
  CharlieBackend.Library/SwaggerExamples/SecretaryController/GetAllSecretariesResponse.cs
  CharlieBackend.Library/SwaggerExamples/SecretaryController/PostSecretaryRequest.cs
  CharlieBackend.Library/SwaggerExamples/SecretaryController/PutSecretaryRequest.cs
Labels: bug

#206 Add StudentService tests
  CharlieBackend.Api.UnitTes/StudentServiceTests.cs
Labels: development

#230 Feature/add file encoding
  CharlieBackend.Api/Controllers/ImportController.cs
  CharlieBackend.Api/SwaggerExamples/ImportController/ImportDataFromFileRequest.cs
  CharlieBackend.Business/CharlieBackend.Business.csproj
  CharlieBackend.Business/Services/FileImportService.cs
  CharlieBackend.Business/Services/Interfaces/IFileImportService.cs
  CharlieBackend.Business/Services/Interfaces/IStudentGroupImportService.cs
  CharlieBackend.Business/Services/Interfaces/IStudentGroupService.cs
  CharlieBackend.Business/Services/Interfaces/IStudentImportService.cs
  CharlieBackend.Business/Services/StudentGroupImportService.cs
  CharlieBackend.Business/Services/StudentGroupService.cs
  CharlieBackend.Business/Services/StudentImportService.cs
  CharlieBackend.Core/DTO/File/ImportFileDto.cs
  CharlieBackend.Core/FileModels/StudentFileModel.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IStudentGroupRepository.cs
  CharlieBackend.Data/Repositories/Impl/StudentGroupRepository.cs
  CharlieBackend.Data/Repositories/Impl/StudentRepository.cs
  CharlieBackend.Root/CompositionRoot.cs
Labels: development

#240 Fix/warningsXML
  CharlieBackend.Api/Controllers/SchedulesController.cs
  CharlieBackend.Api/Extensions/EasyNetQExtension.cs
  CharlieBackend.Api/Middlewares/ExceptionHandleMiddleware.cs
  CharlieBackend.Api/Middlewares/IsAccountActiveMiddleware.cs
  CharlieBackend.Api/Program.cs
  CharlieBackend.Api/Startup.cs
Labels: documentation

#245 Feature/attachments
  CharlieBackend.Api/CharlieBackend.Api.csproj
  CharlieBackend.Api/Controllers/AttachmentsController.cs
  CharlieBackend.Api/Extensions/AzureStorageBlobsExtension.cs
  CharlieBackend.Api/Startup.cs
  CharlieBackend.Api/appsettings.json
  CharlieBackend.Business/CharlieBackend.Business.csproj
  CharlieBackend.Business/Services/AttachmentService.cs
  CharlieBackend.Business/Services/Interfaces/IAttachmentService.cs
  CharlieBackend.Core/AzureStorageBlobAccount.cs
  CharlieBackend.Core/CharlieBackend.Core.csproj
  CharlieBackend.Core/DTO/Attachment/AttachmentDto.cs
  CharlieBackend.Core/DTO/Attachment/DownloadAttachmentDto.cs
  CharlieBackend.Core/Entities/Attachment.cs
  CharlieBackend.Core/Mapping/ModelMappingProfile.cs
  CharlieBackend.Data/ApplicationContext.cs
  CharlieBackend.Data/Repositories/Impl/AttachmentRepository.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IAttachmentRepository.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IUnitOfWork.cs
  CharlieBackend.Data/Repositories/Impl/UnitOfWork.cs
  CharlieBackend.Root/CompositionRoot.cs
  scripts/generate_database.sql
Labels: development, enhancement

#234 Feature/change password
  CharlieBackend.Api.UnitTes/AccountServiceTests.cs
  CharlieBackend.Api/Controllers/AccountsController.cs
  CharlieBackend.Business/Services/AccountService.cs
  CharlieBackend.Business/Services/Interfaces/IAccountService.cs
  CharlieBackend.Core/DTO/Account/ChangeCurrentPasswordDto.cs
  CharlieBackend.Data/Repositories/Impl/AccountRepository.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IAccountRepository.cs
Labels: development, enhancement

#242 Add Courses and StudentGroups to Mentor admin panel
  CharlieBackend.AdminPanel/Models/Mentor/MentorEditViewModel.cs
  CharlieBackend.AdminPanel/Services/MentorService.cs
  CharlieBackend.AdminPanel/Views/Mentors/UpdateMentor.cshtml
  CharlieBackend.Api/Controllers/MentorsController.cs
  CharlieBackend.Business/Services/Interfaces/ICourseService.cs
  CharlieBackend.Business/Services/Interfaces/IMentorService.cs
  CharlieBackend.Business/Services/MentorService.cs
  CharlieBackend.Core/DTO/Mentor/MentorCoursesDto.cs
  CharlieBackend.Core/DTO/Mentor/MentorStudyGroupsDto.cs
  CharlieBackend.Data/Repositories/Impl/CourseRepository.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/ICourseRepository.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IStudentGroupRepository.cs
  CharlieBackend.Data/Repositories/Impl/StudentGroupRepository.cs
Labels: development, enhancement

#133 Feature/dashboard
  CharlieBackend.Api/Controllers/DashboardController.cs
  CharlieBackend.Api/Startup.cs
  CharlieBackend.Api/SwaggerExamples/DashboardController/StudentsClassbookResponse.cs
  CharlieBackend.Api/SwaggerExamples/DashboardController/StudentsResultsResponse.cs
  CharlieBackend.Business/CharlieBackend.Business.csproj
  CharlieBackend.Business/Services/DashboardService.cs
  CharlieBackend.Business/Services/Interfaces/IDashboardService.cs
  CharlieBackend.Core/DTO/Dashboard/DashboardAnalyticsRequestDto.cs
  CharlieBackend.Core/DTO/Dashboard/StudentGroupResults/AverageStudentGroupMarkDto.cs
  CharlieBackend.Core/DTO/Dashboard/StudentGroupResults/AverageStudentGroupVisitDto.cs
  CharlieBackend.Core/DTO/Dashboard/StudentGroupResults/StudentGroupResultType.cs
  CharlieBackend.Core/DTO/Dashboard/StudentGroupResults/StudentsGroupsResultsDto.cs
  CharlieBackend.Core/DTO/Dashboard/StudentsClassbook/ClassbookResultType.cs
  CharlieBackend.Core/DTO/Dashboard/StudentsClassbook/StudentMarkDto.cs
  CharlieBackend.Core/DTO/Dashboard/StudentsClassbook/StudentVisitDto.cs
  CharlieBackend.Core/DTO/Dashboard/StudentsClassbook/StudentsClassbookResultDto.cs
  CharlieBackend.Core/DTO/Dashboard/StudentsRequestDto.cs
  CharlieBackend.Core/DTO/Dashboard/StudentsResults/AverageStudentMarkDto.cs
  CharlieBackend.Core/DTO/Dashboard/StudentsResults/AverageStudentVisitsDto.cs
  CharlieBackend.Core/DTO/Dashboard/StudentsResults/StudentResultType.cs
  CharlieBackend.Core/DTO/Dashboard/StudentsResults/StudentsResultsDto.cs
  CharlieBackend.Core/Extensions/QueryableExtensions.cs
  CharlieBackend.Core/Extensions/ResultExtensionMethods.cs
  CharlieBackend.Core/Extensions/TimeSpanConverter.cs
  CharlieBackend.Data/Repositories/Impl/DashboardRepository.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IDashboardRepository.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IRepository.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IUnitOfWork.cs
  CharlieBackend.Data/Repositories/Impl/Repository.cs
  CharlieBackend.Data/Repositories/Impl/UnitOfWork.cs
  CharlieBackend.Root/CompositionRoot.cs
Labels: development

#251 Moving HashPassword logic from AccountService
  CharlieBackend.Api.UnitTes/AccountServiceTests.cs
  CharlieBackend.Business/Helpers/PasswordHelper.cs
  CharlieBackend.Business/Services/AccountService.cs
  CharlieBackend.Business/Services/Interfaces/IAccountService.cs
Labels: enhancement

#262 Fixed GetStudentAverageMarks() conditions
  CharlieBackend.Data/Repositories/Impl/DashboardRepository.cs
Labels: bug

#258 Fix students admin panel, improved themes admin panel
  CharlieBackend.AdminPanel/Controllers/ThemesController.cs
  CharlieBackend.AdminPanel/Views/Students/AllStudents.cshtml
  CharlieBackend.AdminPanel/Views/Themes/AllThemes.cshtml
  CharlieBackend.AdminPanel/Views/Themes/UpdateTheme.cshtml
  CharlieBackend.Api/Controllers/MentorsController.cs
Labels: bug, enhancement, invalid

#237 Changed Returned type from T to Result<T> in all services
  CharlieBackend.Api.UnitTes/AccountServiceTests.cs
  CharlieBackend.Api.UnitTes/Controllers/LessonsControllerUnitTest.cs
  CharlieBackend.Api.UnitTes/LessonServiceTests.cs
  CharlieBackend.Api/Controllers/AccountsController.cs
  CharlieBackend.Api/Controllers/CoursesController.cs
  CharlieBackend.Api/Controllers/LessonsController.cs
  CharlieBackend.Api/Controllers/MentorsController.cs
  CharlieBackend.Api/Controllers/SchedulesController.cs
  CharlieBackend.Api/Controllers/SecretariesController.cs
  CharlieBackend.Api/Controllers/StudentsController.cs
  CharlieBackend.Business/Services/AccountService.cs
  CharlieBackend.Business/Services/CourseService.cs
  CharlieBackend.Business/Services/Interfaces/IAccountService.cs
  CharlieBackend.Business/Services/Interfaces/ICourseService.cs
  CharlieBackend.Business/Services/Interfaces/ILessonService.cs
  CharlieBackend.Business/Services/Interfaces/IMentorService.cs
  CharlieBackend.Business/Services/Interfaces/ISecretaryService.cs
  CharlieBackend.Business/Services/Interfaces/IStudentService.cs
  CharlieBackend.Business/Services/LessonService.cs
  CharlieBackend.Business/Services/MentorService.cs
  CharlieBackend.Business/Services/SecretaryService.cs
  CharlieBackend.Business/Services/StudentGroupService.cs
  CharlieBackend.Business/Services/StudentImportService.cs
  CharlieBackend.Business/Services/StudentService.cs
  CharlieBackend.Data/Repositories/Impl/AccountRepository.cs
Labels: good first issue, invalid

#269 Create LICENSE
  LICENSE
Labels: documentation

#263 Fix/theme deletion
  CharlieBackend.Business/Services/ThemeService.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IThemeRepository.cs
  CharlieBackend.Data/Repositories/Impl/ThemeRepository.cs
Labels: good first issue

#254 Add GetActiveSecretories method in SecretariesController
  CharlieBackend.Api/Controllers/SecretariesController.cs
  CharlieBackend.Business/Services/Interfaces/ISecretaryService.cs
  CharlieBackend.Business/Services/SecretaryService.cs
  CharlieBackend.Data/ApplicationContext.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/ISecretaryRepository.cs
  CharlieBackend.Data/Repositories/Impl/SecretaryRepository.cs
Labels: good first issue

#270 Fixed coursId validation
  CharlieBackend.Api.UnitTes/StudentGroupServiceTest.cs
  CharlieBackend.Business/Services/StudentGroupService.cs
Labels: good first issue

#281 Added the abilitity to get existing entities IDs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IRepository.cs
  CharlieBackend.Data/Repositories/Impl/Repository.cs
Labels: good first issue

#276 Validation added to import
  CharlieBackend.Core/FileModels/StudentFile.cs
  CharlieBackend.Core/FileModels/StudentGroupFile.cs
Labels: enhancement

#278 Feature/improve attachment
  CharlieBackend.Api/Controllers/AccountsController.cs
  CharlieBackend.Api/Controllers/AttachmentsController.cs
  CharlieBackend.Business/Services/AttachmentService.cs
  CharlieBackend.Business/Services/BlobService.cs
  CharlieBackend.Business/Services/Interfaces/IAttachmentService.cs
  CharlieBackend.Business/Services/Interfaces/IBlobService.cs
  CharlieBackend.Core/DTO/Attachment/AttachmentDto.cs
  CharlieBackend.Core/Entities/Attachment.cs
  CharlieBackend.Data/ApplicationContext.cs
  CharlieBackend.Root/CompositionRoot.cs
  scripts/generate_database.sql
Labels: development, enhancement

#283 Feature/add dashboard service tests
  CharlieBackend.Api.UnitTes/DashboardServiceTest.cs
  CharlieBackend.Business/Services/DashboardService.cs
Labels: development

#272 Add homework controller
  CharlieBackend.Api/Controllers/CoursesController.cs
  CharlieBackend.Api/Controllers/HomeworksController.cs
  CharlieBackend.Api/SwaggerExamples/HomeworksController/CreateHomeworkRequest.cs
  CharlieBackend.Api/SwaggerExamples/HomeworksController/CreateHomeworkResponse.cs
  CharlieBackend.Business/CharlieBackend.Business.csproj
  CharlieBackend.Business/Services/HomeworkService.cs
  CharlieBackend.Business/Services/Interfaces/IHomeworkService.cs
  CharlieBackend.Core/DTO/Homework/CreateHomeworkDto.cs
  CharlieBackend.Core/DTO/Homework/HomeworkDto.cs
  CharlieBackend.Core/Entities/Attachment.cs
  CharlieBackend.Core/Entities/AttachmentOfHomework.cs
  CharlieBackend.Core/Entities/Homework.cs
  CharlieBackend.Core/Entities/Mentor.cs
  CharlieBackend.Core/Entities/StudentGroup.cs
  CharlieBackend.Core/Mapping/ModelMappingProfile.cs
  CharlieBackend.Data/ApplicationContext.cs
  CharlieBackend.Data/Repositories/Impl/AttachmentRepository.cs
  CharlieBackend.Data/Repositories/Impl/HomeworkRepository.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IAttachmentRepository.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IHomeworkRepository.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IThemeRepository.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IUnitOfWork.cs
  CharlieBackend.Data/Repositories/Impl/Repository.cs
  CharlieBackend.Data/Repositories/Impl/UnitOfWork.cs
  CharlieBackend.Root/CompositionRoot.cs
  scripts/generate_database.sql
Labels: development
