Repository ita-social-projects/WhatBackend, pull requests merged in 2020-11, with the labels that each got.

#57 Feature/ExceptionHandleMiddleware
  CharlieBackend.Api/Middlewares/ExceptionHandleMiddleware.cs
  CharlieBackend.Api/Startup.cs
Labels: development, enhancement

#62 Feature/secretary controller
  CharlieBackend.Api/Controllers/SecretariesController.cs
  CharlieBackend.Api/Startup.cs
  CharlieBackend.Business/Services/Interfaces/ISecretaryService.cs
  CharlieBackend.Business/Services/LessonService.cs
  CharlieBackend.Business/Services/SecretaryService.cs
  CharlieBackend.Core/DTO/Secretary/CreateSecretaryDto.cs
  CharlieBackend.Core/DTO/Secretary/SecretaryDto.cs
  CharlieBackend.Core/DTO/Secretary/UpdateSecretaryDto.cs
  CharlieBackend.Core/Entities/Account.cs
  CharlieBackend.Core/Entities/Secretary.cs
  CharlieBackend.Core/Mapping/ModelMappingProfile.cs
  CharlieBackend.Data/ApplicationContext.cs
  CharlieBackend.Data/CharlieBackend.Data.csproj
  CharlieBackend.Data/Repositories/Impl/Interfaces/ISecretaryRepository.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IUnitOfWork.cs
  CharlieBackend.Data/Repositories/Impl/SecretaryRepository.cs
  CharlieBackend.Data/Repositories/Impl/UnitOfWork.cs
  CharlieBackend.Root/CompositionRoot.cs
Labels: development

#65 Add shedule entity and models ( dto )
  CharlieBackend.Core/DTO/Schedule/CreateScheduleDto.cs
  CharlieBackend.Core/DTO/Schedule/ScheduleDto.cs
  CharlieBackend.Core/DTO/Schedule/UpdateScheduleDto.cs
  CharlieBackend.Core/Entities/Schedule.cs
  CharlieBackend.Core/Entities/StudentGroup.cs
  CharlieBackend.Data/ApplicationContext.cs
  scripts/final_script_with_data.sql
  scripts/generate_database.sql
Labels: development, enhancement

#66 Fix/dto and mapping for lesson
  CharlieBackend.Api.UnitTes/Controllers/LessonsControllerUnitTest.cs
  CharlieBackend.Api/Controllers/LessonsController.cs
  CharlieBackend.Business/CharlieBackend.Business.csproj
  CharlieBackend.Business/Services/Interfaces/ILessonService.cs
  CharlieBackend.Business/Services/LessonService.cs
  CharlieBackend.Core/AdapterExtensionMethods.cs
  CharlieBackend.Core/DTO/Lesson/AssignMentorToLessonDto.cs
  CharlieBackend.Core/DTO/Lesson/CreateLessonDto.cs
  CharlieBackend.Core/DTO/Lesson/LessonDto.cs
  CharlieBackend.Core/DTO/Lesson/StudentLessonDto.cs
  CharlieBackend.Core/DTO/Lesson/UpdateLessonDto.cs
  CharlieBackend.Core/DTO/Visit/VisitDto.cs
  CharlieBackend.Core/Entities/Lesson.cs
  CharlieBackend.Core/Mapping/ModelMappingProfile.cs
  CharlieBackend.Core/Models/Lesson/LessonModel.cs
  CharlieBackend.Core/Models/Lesson/StudentLessonModel.cs
  CharlieBackend.Core/Models/Lesson/UpdateLessonModel.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/ILessonRepository.cs
  CharlieBackend.Data/Repositories/Impl/LessonRepository.cs
Labels: enhancement

#80 Fix/add admin rights
  CharlieBackend.Api/Controllers/LessonsController.cs
  CharlieBackend.Api/Controllers/MentorsController.cs
Labels: bug

#96 Fix/exception handle middleware
  CharlieBackend.Api/Middlewares/ExceptionHandleMiddleware.cs
Labels: invalid

#99 AMPQ added and configured, ApproveEvent added
  CharlieBackend.Api/CharlieBackend.Api.csproj
  CharlieBackend.Api/Extensions/EasyNetQExtension.cs
  CharlieBackend.Api/Startup.cs
  CharlieBackend.Api/appsettings.json
  CharlieBackend.Business/CharlieBackend.Business.csproj
  CharlieBackend.Business/Services/MentorService.cs
  CharlieBackend.Business/Services/SecretaryService.cs
  CharlieBackend.Business/Services/StudentService.cs
  CharlieBackend.Core/IntegrationEvents/Abstractions/IEvent.cs
  CharlieBackend.Core/IntegrationEvents/Events/AccountApprovedEvent.cs
Labels: development, enhancement

#94 Basic operations for schedule
  CharlieBackend.Api/Controllers/SchedulesController.cs
  CharlieBackend.Api/Startup.cs
  CharlieBackend.Business/Services/Interfaces/IScheduleService.cs
  CharlieBackend.Business/Services/ScheduleService.cs
  CharlieBackend.Core/DTO/Schedule/CreateScheduleDto.cs
  CharlieBackend.Core/DTO/Schedule/ScheduleDto.cs
  CharlieBackend.Core/DTO/Schedule/UpdateScheduleDto.cs
  CharlieBackend.Core/Mapping/ModelMappingProfile.cs
  CharlieBackend.Core/TimeSpanConverter.cs
  CharlieBackend.Data/ApplicationContext.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IScheduleRepository.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IUnitOfWork.cs
  CharlieBackend.Data/Repositories/Impl/ScheduleRepository.cs
  CharlieBackend.Data/Repositories/Impl/UnitOfWork.cs
  CharlieBackend.Root/CompositionRoot.cs
  scripts/final_script_with_data.sql
  scripts/generate_database.sql
Labels: development, enhancement

#104 Fix/secretary controllers
  CharlieBackend.Api/Controllers/AccountsController.cs
  CharlieBackend.Api/Controllers/MentorsController.cs
  CharlieBackend.Api/Controllers/SecretariesController.cs
  CharlieBackend.Api/Controllers/StudentsController.cs
  CharlieBackend.Business/Services/AccountService.cs
  CharlieBackend.Business/Services/Interfaces/IAccountService.cs
  CharlieBackend.Business/Services/Interfaces/ISecretaryService.cs
  CharlieBackend.Business/Services/MentorService.cs
  CharlieBackend.Business/Services/SecretaryService.cs
  CharlieBackend.Business/Services/StudentService.cs
  CharlieBackend.Core/DTO/Account/AccountDto.cs
  CharlieBackend.Core/DTO/Account/CreateAccountDto.cs
  CharlieBackend.Core/DTO/Lesson/AssignMentorToLessonDto.cs
  CharlieBackend.Core/DTO/Lesson/CreateLessonDto.cs
  CharlieBackend.Core/DTO/Lesson/LessonDto.cs
  CharlieBackend.Core/DTO/Lesson/StudentLessonDto.cs
  CharlieBackend.Core/DTO/Lesson/UpdateLessonDto.cs
  CharlieBackend.Core/DTO/Mentor/UpdateMentorDto.cs
  CharlieBackend.Core/DTO/Secretary/CreateSecretaryDto.cs
  CharlieBackend.Core/DTO/Secretary/SecretaryDto.cs
  CharlieBackend.Core/DTO/Secretary/UpdateSecretaryDto.cs
  CharlieBackend.Core/DTO/Student/UpdateStudentDto.cs
  CharlieBackend.Core/DTO/StudentGroups/CreateStudentGroupDto.cs
  CharlieBackend.Core/DTO/StudentGroups/StudentGroupDto.cs
  CharlieBackend.Core/DTO/StudentGroups/UpdateStudentGroupDto.cs
  CharlieBackend.Core/DTO/StudentGroups/UpdateStudentsForStudentGroup.cs
  CharlieBackend.Core/DTO/Visit/VisitDto.cs
  CharlieBackend.Core/Entities/Account.cs
  CharlieBackend.Core/Entities/Role.cs
  CharlieBackend.Core/Entities/UserRole.cs
  CharlieBackend.Core/IntegrationEvents/Events/AccountApprovedEvent.cs
  CharlieBackend.Core/Mapping/ModelMappingProfile.cs
  CharlieBackend.Core/Models/Secretary/CreateSecretaryModel.cs
  CharlieBackend.Core/Models/Secretary/SecretaryModel.cs
  CharlieBackend.Core/Models/Secretary/UpdateSecretaryModel.cs
  CharlieBackend.Data/Repositories/Impl/AccountRepository.cs
  CharlieBackend.Data/Repositories/Impl/StudentRepository.cs
Labels: bug, invalid

#113 Fix shedule repository injection and refactore service code
  CharlieBackend.Business/Services/ScheduleService.cs
  CharlieBackend.Data/Repositories/Impl/UnitOfWork.cs
Labels: bug

#115 Added secretary role to controllers #111
  CharlieBackend.Api/Controllers/CoursesController.cs
  CharlieBackend.Api/Controllers/LessonsController.cs
  CharlieBackend.Api/Controllers/MentorsController.cs
  CharlieBackend.Api/Controllers/SecretariesController.cs
  CharlieBackend.Api/Controllers/StudentGroupsController.cs
  CharlieBackend.Api/Controllers/StudentsController.cs
  CharlieBackend.Api/Controllers/ThemesController.cs
Labels: bug

#117 Fix generate_database.sql secretary table
  scripts/generate_database.sql
Labels: bug

#114 Feature/add integration events into what backend
  CharlieBackend.Api/Controllers/MentorsController.cs
  CharlieBackend.Business/Services/AccountService.cs
  CharlieBackend.Business/Services/EmailCredentialsSenderService.cs
  CharlieBackend.Business/Services/Interfaces/ICredentialsSenderService.cs
  CharlieBackend.Business/Services/Interfaces/INotificationService.cs
  CharlieBackend.Business/Services/MentorService.cs
  CharlieBackend.Business/Services/MessageSender.cs
  CharlieBackend.Business/Services/NotificationService.cs
  CharlieBackend.Business/Services/SecretaryService.cs
  CharlieBackend.Business/Services/StudentService.cs
  CharlieBackend.Core/CharlieBackend.Core.csproj
  CharlieBackend.Core/DTO/EmailData/EmailData.cs
  CharlieBackend.Root/CompositionRoot.cs
  WhatBackend.EmailRenderService/WhatBackend.EmailRenderService/Controllers/HomeController.cs
  WhatBackend.EmailRenderService/WhatBackend.EmailRenderService/IntegrationEvents/EventHandling/AccountApprovedConsumer.cs
  WhatBackend.EmailRenderService/WhatBackend.EmailRenderService/IntegrationEvents/MessageDispatcher.cs
  WhatBackend.EmailRenderService/WhatBackend.EmailRenderService/Program.cs
  WhatBackend.EmailRenderService/WhatBackend.EmailRenderService/Properties/launchSettings.json
  WhatBackend.EmailRenderService/WhatBackend.EmailRenderService/Startup.cs
  WhatBackend.EmailRenderService/WhatBackend.EmailRenderService/WhatBackend.EmailRenderService.csproj
  WhatBackend.EmailRenderService/WhatBackend.EmailRenderService/WhatBackend.EmailRenderService.sln
  WhatBackend.EmailRenderService/WhatBackend.EmailRenderService/appsettings.Development.json
  WhatBackend.EmailRenderService/WhatBackend.EmailRenderService/appsettings.json
Labels: development, enhancement

#119 Feature/create email sending service
  CharlieBackend.Core/CharlieBackend.Core.csproj
  CharlieBackend.Core/DTO/EmailData/EmailData.cs
  WhatBackend.EmailSendingService/WhatBackend.EmailSendingService.sln
  WhatBackend.EmailSendingService/WhatBackend.EmailSendingService/Program.cs
  WhatBackend.EmailSendingService/WhatBackend.EmailSendingService/Properties/launchSettings.json
  WhatBackend.EmailSendingService/WhatBackend.EmailSendingService/Services/EmailSender.cs
  WhatBackend.EmailSendingService/WhatBackend.EmailSendingService/Services/EmailSendingConsumer.cs
  WhatBackend.EmailSendingService/WhatBackend.EmailSendingService/Services/Interfaces/IEmailSender.cs
  WhatBackend.EmailSendingService/WhatBackend.EmailSendingService/Services/MessageDispatcher.cs
  WhatBackend.EmailSendingService/WhatBackend.EmailSendingService/Startup.cs
  WhatBackend.EmailSendingService/WhatBackend.EmailSendingService/WhatBackend.EmailSendingService.csproj
  WhatBackend.EmailSendingService/WhatBackend.EmailSendingService/appsettings.Development.json
  WhatBackend.EmailSendingService/WhatBackend.EmailSendingService/appsettings.json
Labels: development, enhancement

#137 Fix/schedules
  CharlieBackend.Api/Controllers/SchedulesController.cs
  CharlieBackend.Business/Services/Interfaces/IScheduleService.cs
  CharlieBackend.Business/Services/ScheduleService.cs
  CharlieBackend.Core/DTO/Theme/CreateThemeDto.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IScheduleRepository.cs
  CharlieBackend.Data/Repositories/Impl/ScheduleRepository.cs
Labels: invalid

#135 UpdateLessonDto mapping fix #131
  CharlieBackend.Business/Services/LessonService.cs
  CharlieBackend.Core/DTO/Lesson/UpdateLessonDto.cs
  CharlieBackend.Core/DTO/Visit/VisitDto.cs
  CharlieBackend.Core/Mapping/ModelMappingProfile.cs
Labels: bug

#122 Feature/add import controller
  CharlieBackend.Api/CharlieBackend.Api.csproj
  CharlieBackend.Api/Controllers/ImportController.cs
  CharlieBackend.Business/CharlieBackend.Business.csproj
  CharlieBackend.Business/Services/FileImportService.cs
  CharlieBackend.Business/Services/Interfaces/IFileImportService.cs
  CharlieBackend.Core/CharlieBackend.Core.csproj
  CharlieBackend.Core/DTO/File/ImportFileDto.cs
  CharlieBackend.Core/FileModels/StudentGroupFileModel.cs
  CharlieBackend.Data/CharlieBackend.Data.csproj
  CharlieBackend.Root/CompositionRoot.cs
Labels: development

#138 Feature/add import controller
  CharlieBackend.Api/CharlieBackend.Api.csproj
  CharlieBackend.Api/Controllers/ImportController.cs
  CharlieBackend.Business/CharlieBackend.Business.csproj
  CharlieBackend.Business/Services/FileImportService.cs
  CharlieBackend.Business/Services/Interfaces/IFileImportService.cs
  CharlieBackend.Core/CharlieBackend.Core.csproj
  CharlieBackend.Core/DTO/File/ImportFileDto.cs
  CharlieBackend.Core/FileModels/StudentGroupFileModel.cs
  CharlieBackend.Data/CharlieBackend.Data.csproj
  CharlieBackend.Root/CompositionRoot.cs
Labels: development

#143 Fixed LessonDto bug and lessonDtoMapping
  CharlieBackend.Business/Services/LessonService.cs
  CharlieBackend.Core/DTO/Lesson/UpdateLessonDto.cs
  CharlieBackend.Core/DTO/Visit/VisitDto.cs
  CharlieBackend.Core/Mapping/ModelMappingProfile.cs
Labels: bug

#134 Fix Result<T> to remove NULL and NONE
  CharlieBackend.Api/Controllers/SchedulesController.cs
  CharlieBackend.Api/Controllers/StudentGroupsController.cs
  CharlieBackend.Business/Services/AccountService.cs
  CharlieBackend.Business/Services/MentorService.cs
  CharlieBackend.Business/Services/ScheduleService.cs
  CharlieBackend.Business/Services/SecretaryService.cs
  CharlieBackend.Business/Services/StudentGroupService.cs
  CharlieBackend.Business/Services/StudentService.cs
  CharlieBackend.Core/Models/ResultModel/ErrorCode.cs
  CharlieBackend.Core/Models/ResultModel/Result.cs
  CharlieBackend.Core/ResultExtensionMethods.cs
Labels: bug

#159 Fix/lesson dto
  CharlieBackend.Api/Controllers/LessonsController.cs
  CharlieBackend.Business/Services/Interfaces/ILessonService.cs
  CharlieBackend.Business/Services/LessonService.cs
  CharlieBackend.Core/DTO/Lesson/LessonDto.cs
  CharlieBackend.Core/DTO/Lesson/UpdateLessonDto.cs
  CharlieBackend.Core/DTO/Theme/CreateThemeDto.cs
  CharlieBackend.Core/DTO/Visit/VisitDto.cs
  CharlieBackend.Core/Mapping/ModelMappingProfile.cs
Labels: invalid

#156 Added Json format of Error reply
  CharlieBackend.Core/DTO/Result/ErrorDto.cs
  CharlieBackend.Core/Models/ResultModel/Error.cs
  CharlieBackend.Core/Models/ResultModel/Result.cs
  CharlieBackend.Core/ResultExtensionMethods.cs
Labels: development

#163 Add Swashbuckle, XML comments
  CharlieBackend.Api/CharlieBackend.Api.csproj
  CharlieBackend.Api/Controllers/SecretariesController.cs
  CharlieBackend.Api/Startup.cs
  CharlieBackend.Api/SwaggerExamples/SecretariesController/GetAllSecretariesResponse.cs
  CharlieBackend.Api/SwaggerExamples/SecretariesController/PostSecretaryRequest.cs
  CharlieBackend.Api/SwaggerExamples/SecretariesController/PutSecretaryRequest.cs
  CharlieBackend.Library/CharlieBackend.Library.csproj
  CharlieBackend.Library/SwaggerExamples/SecretaryController/GetAllSecretariesResponse.cs
  CharlieBackend.Library/SwaggerExamples/SecretaryController/PostSecretaryRequest.cs
  CharlieBackend.Library/SwaggerExamples/SecretaryController/PutSecretaryRequest.cs
Labels: development

#167 Fix theme controller to work with Result T
  CharlieBackend.Api.UnitTes/Controllers/ThemesControllerTests.cs
  CharlieBackend.Api/Controllers/ThemesController.cs
  CharlieBackend.Business/Services/Interfaces/IThemeService.cs
  CharlieBackend.Business/Services/ThemeService.cs
Labels: bug, enhancement

#174 Fix schedule service and controller to work with Result T
  CharlieBackend.Api/Controllers/SchedulesController.cs
  CharlieBackend.Business/Services/Interfaces/IScheduleService.cs
  CharlieBackend.Business/Services/ScheduleService.cs
Labels: invalid

#183 Fix 401 error in swagger
  CharlieBackend.Api/Startup.cs
Labels: bug

#186 Feature/add mentor unit tests
  CharlieBackend.Api.UnitTes/MentorServiceTests.cs
Labels: development

#187 Feature/add lesson service tests
  CharlieBackend.Api.UnitTes/LessonServiceTests.cs
Labels: development

#180 Feature/admin panel themes
  CharlieBackend.AdminPanel/Controllers/ThemesController.cs
  CharlieBackend.AdminPanel/Models/Theme/ThemeViewModel.cs
  CharlieBackend.AdminPanel/Services/Interfaces/IThemeService.cs
  CharlieBackend.AdminPanel/Services/ThemeService.cs
  CharlieBackend.AdminPanel/Startup.cs
  CharlieBackend.AdminPanel/Views/Shared/_Layout.cshtml
  CharlieBackend.AdminPanel/Views/Themes/AllThemes.cshtml
  CharlieBackend.AdminPanel/Views/Themes/UpdateTheme.cshtml
  CharlieBackend.Core/Entities/Theme.cs
Labels: development, enhancement

#198 EmailRenderService fix
  CharlieBackend.Business/Services/NotificationService.cs
  WhatBackend.EmailRenderService/WhatBackend.EmailRenderService/IntegrationEvents/EventHandling/AccountApprovedHanlder.cs
  WhatBackend.EmailRenderService/WhatBackend.EmailRenderService/IntegrationEvents/EventHandling/RegistrationSuccessHanlder.cs
  WhatBackend.EmailRenderService/WhatBackend.EmailRenderService/IntegrationEvents/MessageDispatcher.cs
  WhatBackend.EmailRenderService/WhatBackend.EmailRenderService/Startup.cs
  WhatBackend.EmailSendingService/WhatBackend.EmailSendingService/Properties/launchSettings.json
  WhatBackend.EmailSendingService/WhatBackend.EmailSendingService/Services/EmailSendingConsumer.cs
  WhatBackend.EmailSendingService/WhatBackend.EmailSendingService/Startup.cs
Labels: bug

#196 Feature/add account unit tests
  CharlieBackend.Api.UnitTes/AccountServiceTests.cs
  CharlieBackend.Api.UnitTes/MentorServiceTests.cs
  CharlieBackend.Api/SwaggerExamples/AccountsController/PostAccountResponse.cs
  CharlieBackend.Business/Services/AccountService.cs
Labels: development
