Repository ita-social-projects/WhatBackend, pull requests merged in 2021-03, with the labels that each got.

#437 Deleted all unnecessary .WithMessage(...) in fluent validation
  CharlieBackend.Api/Validators/AccountDTOValidators/AccountDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/AuthenticationDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/ChangeCurrentPasswordDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/CreateAccountDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/ForgotPasswordDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/ResetPasswordDtoValidator.cs
Labels: enhancement

#415 Add Courses View and Controller to Admin Panel
  CharlieBackend.AdminPanel/Controllers/CoursesController.cs
  CharlieBackend.AdminPanel/Models/Course/CourseViewModel.cs
  CharlieBackend.AdminPanel/Services/CourseService.cs
  CharlieBackend.AdminPanel/Services/Interfaces/ICourseService.cs
  CharlieBackend.AdminPanel/Services/Interfaces/IMentorService.cs
  CharlieBackend.AdminPanel/Services/Interfaces/IStudentService.cs
  CharlieBackend.AdminPanel/Services/MentorService.cs
  CharlieBackend.AdminPanel/Services/StudentService.cs
  CharlieBackend.AdminPanel/Views/Courses/AllCourses.cshtml
  CharlieBackend.AdminPanel/Views/Shared/_Layout.cshtml
Labels: development

#452 Fix comparison operator in GetEventsFiltered()
  CharlieBackend.Api.UnitTes/ScheduleServiceTests.cs
  CharlieBackend.Business/Services/ScheduleServiceFolder/ScheduleService.cs
Labels: bug

#454 Added field storage to the class EventOccurrenceDTO
  CharlieBackend.Core/DTO/Schedule/EventOccurrenceDTO.cs
Labels: development

#457 Added mentor activation on the admin panel
  CharlieBackend.AdminPanel/Controllers/MentorsController.cs
  CharlieBackend.AdminPanel/Services/Interfaces/IMentorService.cs
  CharlieBackend.AdminPanel/Services/MentorService.cs
  CharlieBackend.AdminPanel/Utils/ApiUtil.cs
  CharlieBackend.AdminPanel/Utils/HttpUtil.cs
  CharlieBackend.AdminPanel/Utils/Interfaces/IApiUtil.cs
  CharlieBackend.AdminPanel/Utils/Interfaces/IHttpUtil.cs
  CharlieBackend.AdminPanel/Views/Mentors/AllMentors.cshtml
Labels: development

#456 Add method for POST requests in IApiUtil
  CharlieBackend.AdminPanel/Utils/ApiUtil.cs
  CharlieBackend.AdminPanel/Utils/Interfaces/IApiUtil.cs
Labels: enhancement

#461 Added activate option for Students in Admin Panel
  CharlieBackend.AdminPanel/Controllers/StudentsController.cs
  CharlieBackend.AdminPanel/Services/Interfaces/IStudentService.cs
  CharlieBackend.AdminPanel/Services/StudentService.cs
  CharlieBackend.AdminPanel/Utils/ApiUtil.cs
  CharlieBackend.AdminPanel/Utils/HttpUtil.cs
  CharlieBackend.AdminPanel/Utils/Interfaces/IHttpUtil.cs
  CharlieBackend.AdminPanel/Views/Students/AllStudents.cshtml
  cli_scripts/run-localhost-what-api.cmd.command
Labels: development

#462 Add enable option for courses
  CharlieBackend.AdminPanel/Controllers/CoursesController.cs
  CharlieBackend.AdminPanel/Services/CourseService.cs
  CharlieBackend.AdminPanel/Services/Interfaces/ICourseService.cs
  CharlieBackend.AdminPanel/Views/Courses/AllCourses.cshtml
Labels: development

#467 Added new endpoint GetScheduleEventById
  CharlieBackend.Api/Controllers/SchedulesController.cs
  CharlieBackend.Business/Services/Interfaces/IScheduleService.cs
  CharlieBackend.Business/Services/ScheduleServiceFolder/ScheduleService.cs
Labels: development

#469 Fixed wrong data order while deleting EventOccurrences
  CharlieBackend.Business/Services/ScheduleServiceFolder/ScheduleService.cs
  scripts/final_script_with_data.sql
Labels: bug

#460 Add services for calendar
  CharlieBackend.AdminPanel/Controllers/CalendarController.cs
  CharlieBackend.AdminPanel/Extensions/Extensions.cs
  CharlieBackend.AdminPanel/Models/Calendar/CalendarCourseViewModel.cs
  CharlieBackend.AdminPanel/Models/Calendar/CalendarEventOccurrenceViewModel.cs
  CharlieBackend.AdminPanel/Models/Calendar/CalendarMentorViewModel.cs
  CharlieBackend.AdminPanel/Models/Calendar/CalendarScheduledEventViewModel.cs
  CharlieBackend.AdminPanel/Models/Calendar/CalendarStudentGroupViewModel.cs
  CharlieBackend.AdminPanel/Models/Calendar/CalendarStudentViewModel.cs
  CharlieBackend.AdminPanel/Models/Calendar/CalendarThemeViewModel.cs
  CharlieBackend.AdminPanel/Models/Calendar/CalendarViewModel.cs
  CharlieBackend.AdminPanel/Models/Mapping/ViewModelMapping.cs
  CharlieBackend.AdminPanel/Services/CalendarService.cs
  CharlieBackend.AdminPanel/Services/Interfaces/ICalendarService.cs
  CharlieBackend.AdminPanel/Services/Interfaces/IScheduleService.cs
  CharlieBackend.AdminPanel/Services/ScheduleService.cs
  CharlieBackend.AdminPanel/Startup.cs
  CharlieBackend.Api/Controllers/SchedulesController.cs
  CharlieBackend.Business/Services/Interfaces/IScheduleService.cs
  CharlieBackend.Business/Services/ScheduleServiceFolder/ScheduleService.cs
Labels: development

#435 Fluent Validation for password
  CharlieBackend.Api/Validators/AccountDTOValidators/AccountDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/AuthenticationDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/ChangeCurrentPasswordDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/CreateAccountDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/ForgotPasswordDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/ResetPasswordDtoValidator.cs
  CharlieBackend.Business/Helpers/PasswordHelper.cs
  CharlieBackend.Business/Helpers/ValidationConstants.cs
  CharlieBackend.Business/Services/AccountService.cs
Labels: enhancement

#410 Test for Homework Service
  CharlieBackend.Api.UnitTes/HomeworkServiceTests.cs
  CharlieBackend.Api.UnitTes/StudentServiceTests.cs
Labels: development

#473 Added deleting single scheduled events by id
  CharlieBackend.Api/Controllers/SchedulesController.cs
  CharlieBackend.Business/Services/Interfaces/IScheduleService.cs
  CharlieBackend.Business/Services/ScheduleServiceFolder/ScheduleService.cs
Labels: development

#472 Add create option for course
  CharlieBackend.AdminPanel/Controllers/CoursesController.cs
  CharlieBackend.AdminPanel/Services/CourseService.cs
  CharlieBackend.AdminPanel/Services/Interfaces/ICourseService.cs
  CharlieBackend.AdminPanel/Views/Courses/AllCourses.cshtml
Labels: development

#477 Generated and modified hash of password and salt
  CharlieBackend.Business/Helpers/PasswordHelper.cs
  scripts/final_script_with_data.sql
Labels: bug

#475 Now we can delete event occurance without passing dates
  CharlieBackend.Business/Services/ScheduleServiceFolder/ScheduleService.cs
Labels: bug

#430 Add avatar as optional part of account
  CharlieBackend.Api.UnitTes/MentorServiceTests.cs
  CharlieBackend.Api.UnitTes/SecretaryServiceTests.cs
  CharlieBackend.Api.UnitTes/StudentServiceTests.cs
  CharlieBackend.Api/Controllers/AttachmentsController.cs
  CharlieBackend.Api/Controllers/MentorsController.cs
  CharlieBackend.Api/Controllers/SecretariesController.cs
  CharlieBackend.Api/Controllers/StudentsController.cs
  CharlieBackend.Business/Services/AttachmentService.cs
  CharlieBackend.Business/Services/BlobService.cs
  CharlieBackend.Business/Services/Interfaces/IAttachmentService.cs
  CharlieBackend.Business/Services/Interfaces/IBlobService.cs
  CharlieBackend.Business/Services/Interfaces/IMentorService.cs
  CharlieBackend.Business/Services/Interfaces/ISecretaryService.cs
  CharlieBackend.Business/Services/Interfaces/IStudentService.cs
  CharlieBackend.Business/Services/MentorService.cs
  CharlieBackend.Business/Services/SecretaryService.cs
  CharlieBackend.Business/Services/StudentService.cs
  CharlieBackend.Core/AzureStorageBlobAccount.cs
  CharlieBackend.Core/DTO/Mentor/MentorDetailsDto.cs
  CharlieBackend.Core/DTO/Secretary/SecretaryDetailsDto.cs
  CharlieBackend.Core/DTO/Student/StudentDetailsDto.cs
  CharlieBackend.Core/Entities/Account.cs
  CharlieBackend.Core/Entities/Attachment.cs
  CharlieBackend.Core/Mapping/ModelMappingProfile.cs
  CharlieBackend.Data/Configurations/AccountEntityConfiguration.cs
  CharlieBackend.Data/Repositories/Impl/AccountRepository.cs
  CharlieBackend.Data/Repositories/Impl/MentorRepository.cs
  CharlieBackend.Data/Repositories/Impl/SecretaryRepository.cs
  CharlieBackend.Data/Repositories/Impl/StudentRepository.cs
  scripts/generate_database.sql
Labels: development

#429 Fix for not found lesson check
  CharlieBackend.Api.UnitTes/LessonServiceTests.cs
  CharlieBackend.Api/Controllers/LessonsController.cs
  CharlieBackend.Business/Services/LessonService.cs
Labels: bug

#423 Update unit tests for MentorService
  CharlieBackend.Api.UnitTes/MentorServiceTests.cs
Labels: enhancement

#422 Unit Tests for Update and Delete in Schedule Service
  CharlieBackend.Api.UnitTes/ScheduleServiceTests.cs
  CharlieBackend.Business/Services/ScheduleServiceFolder/ScheduleService.cs
Labels: development

#372 Refactoring in IsAccountActiveMiddleware
  CharlieBackend.Api/Controllers/StudentsController.cs
  CharlieBackend.Api/Middlewares/IsAccountActiveMiddleware.cs
Labels: good first issue

#409 Update unit tests for Dashboard Service
  CharlieBackend.Api.UnitTes/DashboardServiceTest.cs
Labels: enhancement

#464 Calendar in admin panel
  CharlieBackend.AdminPanel/Controllers/CalendarController.cs
  CharlieBackend.AdminPanel/HtmlHelpers/CalendarHelper.cs
  CharlieBackend.AdminPanel/Services/Interfaces/IScheduleService.cs
  CharlieBackend.AdminPanel/Views/Calendar/CalendarBody.cshtml
  CharlieBackend.AdminPanel/Views/Calendar/Index.cshtml
  CharlieBackend.AdminPanel/Views/Shared/_Layout.cshtml
  CharlieBackend.Core/DTO/Schedule/ScheduledEventFilterRequestDTO.cs
  cli_scripts/run-localhost-what-api.cmd
Labels: development

#482 Separated logic of working with schedules and events
  CharlieBackend.Api.UnitTes/ScheduleServiceTests.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/UpdateScheduledEventDTOValidatorTests.cs
  CharlieBackend.Api/CharlieBackend.Api.csproj
  CharlieBackend.Api/Controllers/EventsController.cs
  CharlieBackend.Api/Controllers/SchedulesController.cs
  CharlieBackend.Api/Middlewares/ExceptionHandleMiddleware.cs
  CharlieBackend.Api/Startup.cs
  CharlieBackend.Api/Validators/ScheduledEventDTOValidators/UpdateScheduledEventDTOValidator.cs
  CharlieBackend.Business/Exceptions/EntityValidationException.cs
  CharlieBackend.Business/Helpers/ExceptionsConstants.cs
  CharlieBackend.Business/Helpers/ValidationConstants.cs
  CharlieBackend.Business/Services/Interfaces/IEventsService.cs
  CharlieBackend.Business/Services/Interfaces/IScheduleService.cs
  CharlieBackend.Business/Services/ScheduleServiceFolder/EventsService.cs
  CharlieBackend.Business/Services/ScheduleServiceFolder/Helpers/SchedulesEventsValidator.cs
  CharlieBackend.Business/Services/ScheduleServiceFolder/Helpers/SchedulesUpdater.cs
  CharlieBackend.Business/Services/ScheduleServiceFolder/ScheduleService.cs
  CharlieBackend.Data/CharlieBackend.Data.csproj
  CharlieBackend.Data/Exceptions/NotFoundExceptions.cs
  CharlieBackend.Data/Repositories/Impl/ScheduledEventRepository.cs
  CharlieBackend.Root/CompositionRoot.cs
Labels: development

#487 Move API endpoints for CourseService into ApplicationSettings
  CharlieBackend.AdminPanel/ApplicationSettings.cs
  CharlieBackend.AdminPanel/Services/CourseService.cs
  CharlieBackend.AdminPanel/appsettings.json
Labels: enhancement

#490 Check is lesson done
  CharlieBackend.Api.UnitTes/LessonServiceTests.cs
  CharlieBackend.Api/Controllers/LessonsController.cs
  CharlieBackend.Business/Services/Interfaces/ILessonService.cs
  CharlieBackend.Business/Services/LessonService.cs
Labels: development
