Repository ita-social-projects/WhatBackend, pull requests merged in 2021-01, with the labels that each got.

#286 Add Validation in CreateLesson and UpdateLesson methods
  CharlieBackend.Api.UnitTes/LessonServiceTests.cs
  CharlieBackend.Business/Services/LessonService.cs
  CharlieBackend.Business/Services/StudentGroupService.cs
  CharlieBackend.Core/DTO/Visit/VisitDto.cs
  CharlieBackend.Core/Entities/Visit.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IStudentGroupRepository.cs
  CharlieBackend.Data/Repositories/Impl/StudentGroupRepository.cs
Labels: development, good first issue

#290 Add update homework
  CharlieBackend.Api/Controllers/HomeworksController.cs
  CharlieBackend.Api/Controllers/StudentGroupsController.cs
  CharlieBackend.Api/Controllers/ThemesController.cs
  CharlieBackend.Api/SwaggerExamples/HomeworksController/CreateHomeworkRequest.cs
  CharlieBackend.Api/SwaggerExamples/HomeworksController/GetHomeworksResponse.cs
  CharlieBackend.Business/Services/HomeworkService.cs
  CharlieBackend.Business/Services/Interfaces/IHomeworkService.cs
  CharlieBackend.Core/DTO/Homework/HomeworkRequestDto.cs
  CharlieBackend.Data/Repositories/Impl/HomeworkRepository.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IHomeworkRepository.cs
Labels: development

#289 Added mentors and students ids validation
  CharlieBackend.Api.UnitTes/StudentGroupServiceTest.cs
  CharlieBackend.Business/Services/StudentGroupService.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IRepository.cs
  CharlieBackend.Data/Repositories/Impl/Repository.cs
Labels: good first issue

#291 Fixed Update of Student Groups
  CharlieBackend.Business/Services/StudentService.cs
  CharlieBackend.Data/Repositories/Impl/StudentRepository.cs
Labels: bug, good first issue

#299 fixed bug with result<T> reterning
  CharlieBackend.Api/Controllers/MentorsController.cs
  CharlieBackend.Api/Controllers/StudentsController.cs
  CharlieBackend.Business/Services/StudentService.cs
Labels: bug, invalid

#295 Fix bug in Dashbord Repository
  CharlieBackend.Api.UnitTes/DashboardServiceTest.cs
  CharlieBackend.Core/DTO/Dashboard/StudentGroupResults/AverageStudentGroupMarkDto.cs
  CharlieBackend.Core/DTO/Dashboard/StudentsResults/AverageStudentMarkDto.cs
  CharlieBackend.Data/Repositories/Impl/DashboardRepository.cs
Labels: bug

#292 Create new endPoint for MentorController
  CharlieBackend.Api.UnitTes/MentorServiceTests.cs
  CharlieBackend.Api/Controllers/LessonsController.cs
  CharlieBackend.Api/Controllers/MentorsController.cs
  CharlieBackend.Business/Services/Interfaces/ILessonService.cs
  CharlieBackend.Business/Services/Interfaces/IMentorService.cs
  CharlieBackend.Business/Services/LessonService.cs
  CharlieBackend.Business/Services/MentorService.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/ILessonRepository.cs
  CharlieBackend.Data/Repositories/Impl/LessonRepository.cs
Labels: good first issue

#326 Rework Homework entity
  CharlieBackend.Api/Controllers/StudentGroupsController.cs
  CharlieBackend.Api/SwaggerExamples/HomeworksController/CreateHomeworkRequest.cs
  CharlieBackend.Api/SwaggerExamples/HomeworksController/CreateHomeworkResponse.cs
  CharlieBackend.Api/SwaggerExamples/HomeworksController/GetHomeworksResponse.cs
  CharlieBackend.Business/Services/HomeworkService.cs
  CharlieBackend.Business/Services/Interfaces/IHomeworkService.cs
  CharlieBackend.Core/DTO/Homework/HomeworkDto.cs
  CharlieBackend.Core/DTO/Homework/HomeworkRequestDto.cs
  CharlieBackend.Core/Entities/Homework.cs
  CharlieBackend.Core/Entities/Lesson.cs
  CharlieBackend.Core/Entities/Mentor.cs
  CharlieBackend.Core/Entities/StudentGroup.cs
  CharlieBackend.Data/ApplicationContext.cs
  CharlieBackend.Data/Repositories/Impl/HomeworkRepository.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IHomeworkRepository.cs
  scripts/generate_database.sql
Labels: development

#301 Unit test and bug fixing in dashboard repository
  CharlieBackend.Api.UnitTes/CharlieBackend.Api.UnitTest.csproj
  CharlieBackend.Api.UnitTes/RepositoriesTests/DashboardRepositoryTest.cs
  CharlieBackend.Api/Startup.cs
  CharlieBackend.Data/ApplicationContext.cs
  CharlieBackend.Data/Repositories/Impl/DashboardRepository.cs
Labels: development, enhancement, invalid

#336 Fixed validation of the dates
  CharlieBackend.Business/Services/StudentGroupService.cs
Labels: bug, good first issue

#313 Add filter for mentor lessons
  CharlieBackend.Api/Controllers/MentorsController.cs
  CharlieBackend.Api/SwaggerExamples/MentorsController/PostFilterLessonsRequest.cs
  CharlieBackend.Business/Services/Interfaces/ILessonService.cs
  CharlieBackend.Business/Services/LessonService.cs
  CharlieBackend.Core/DTO/Lesson/FilterLessonsRequestDto.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/ILessonRepository.cs
  CharlieBackend.Data/Repositories/Impl/LessonRepository.cs
Labels: development, enhancement

#305 Rework GetCourses in CoursesController
  CharlieBackend.Api/Controllers/CoursesController.cs
  CharlieBackend.Business/Services/CourseService.cs
  CharlieBackend.Business/Services/Interfaces/ICourseService.cs
  CharlieBackend.Core/DTO/Course/CourseDto.cs
  CharlieBackend.Data/Repositories/Impl/CourseRepository.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/ICourseRepository.cs
Labels: development

#352 Reworked file import and provided refactoring
  CharlieBackend.Api/Controllers/ImportController.cs
  CharlieBackend.Api/SwaggerExamples/ImportController/ImportDataFromFileResponse.cs
  CharlieBackend.Business/Services/FileServices/BaseFileService.cs
  CharlieBackend.Business/Services/FileServices/FileExtension.cs
  CharlieBackend.Business/Services/FileServices/GroupsWorksheetHeader.cs
  CharlieBackend.Business/Services/FileServices/IBaseFileService.cs
  CharlieBackend.Business/Services/FileServices/IXLSFileService.cs
  CharlieBackend.Business/Services/FileServices/StudentsWorksheetHeader.cs
  CharlieBackend.Business/Services/FileServices/XLSFileService.cs
  CharlieBackend.Business/Services/Interfaces/IStudentGroupImportService.cs
  CharlieBackend.Business/Services/Interfaces/IStudentImportService.cs
  CharlieBackend.Business/Services/Interfaces/IThemeImportService.cs
  CharlieBackend.Business/Services/StudentGroupImportService.cs
  CharlieBackend.Business/Services/StudentImportService.cs
  CharlieBackend.Business/Services/ThemeImportService.cs
  CharlieBackend.Core/DTO/StudentGroups/ImportStudentGroupDto.cs
  CharlieBackend.Core/FileModels/StudentFile.cs
  CharlieBackend.Core/FileModels/StudentGroupFile.cs
  CharlieBackend.Core/FileModels/ThemeFile.cs
  CharlieBackend.Core/Mapping/ModelMappingProfile.cs
  CharlieBackend.Root/CompositionRoot.cs
Labels: bug

#328 Added new endpoint to get active student groups by date
  CharlieBackend.Api/Controllers/StudentGroupsController.cs
  CharlieBackend.Business/Services/Interfaces/IStudentGroupService.cs
  CharlieBackend.Business/Services/StudentGroupService.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IStudentGroupRepository.cs
  CharlieBackend.Data/Repositories/Impl/StudentGroupRepository.cs
Labels: development

#309 Fixed student group name validation
  CharlieBackend.Api.UnitTes/StudentGroupServiceTest.cs
  CharlieBackend.Business/Services/StudentGroupService.cs
Labels: bug

#339 Remove mentor from Authorize roles in PutStudent endpoint
  CharlieBackend.Api/Controllers/StudentsController.cs
Labels: good first issue

#340 add endpoint descriptions in AttachmentsController #308
  CharlieBackend.Api/Controllers/AttachmentsController.cs
Labels: documentation, good first issue
