Repository ita-social-projects/WhatBackend, pull requests merged in 2021-02, with the labels that each got.

#341 Remove GetStudentLessons from LessonsController
  CharlieBackend.Api/Controllers/LessonsController.cs
  CharlieBackend.Api/Controllers/StudentsController.cs
Labels: bug, good first issue

#331 Fix Internal Server Error on Wrong Password
  CharlieBackend.Business/Services/AccountService.cs
Labels: bug, good first issue

#349 Add CurrentUserService
  CharlieBackend.Api.UnitTes/DashboardServiceTest.cs
  CharlieBackend.Api.UnitTes/LessonServiceTests.cs
  CharlieBackend.Api.UnitTes/TestBase.cs
  CharlieBackend.Api/Controllers/AttachmentsController.cs
  CharlieBackend.Api/Controllers/DashboardController.cs
  CharlieBackend.Api/Controllers/MentorsController.cs
  CharlieBackend.Api/Startup.cs
  CharlieBackend.Business/Services/AttachmentService.cs
  CharlieBackend.Business/Services/CurrentUserService.cs
  CharlieBackend.Business/Services/DashboardService.cs
  CharlieBackend.Business/Services/Interfaces/IAttachmentService.cs
  CharlieBackend.Business/Services/Interfaces/ICurrentUserService.cs
  CharlieBackend.Business/Services/Interfaces/IDashboardService.cs
  CharlieBackend.Business/Services/Interfaces/ILessonService.cs
  CharlieBackend.Business/Services/LessonService.cs
  CharlieBackend.Root/CompositionRoot.cs
Labels: development, enhancement

#348 Fix password validation
  CharlieBackend.Api.UnitTes/AccountServiceTests.cs
  CharlieBackend.Business/Helpers/PasswordHelper.cs
  CharlieBackend.Business/Services/AccountService.cs
Labels: good first issue

#375 Update README with a wiki link
  README.md
Labels: documentation

#333 fix validation in lessons controller
  CharlieBackend.Api.UnitTes/LessonServiceTests.cs
  CharlieBackend.Api/appsettings.json
  CharlieBackend.Business/Services/LessonService.cs
Labels: bug, good first issue

#365 Merged get groups by date endpoints logic into get all student groups
  CharlieBackend.Api/Controllers/StudentGroupsController.cs
  CharlieBackend.Business/Services/Interfaces/IStudentGroupService.cs
  CharlieBackend.Business/Services/StudentGroupService.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/IStudentGroupRepository.cs
  CharlieBackend.Data/Repositories/Impl/StudentGroupRepository.cs
Labels: enhancement

#388 Send one request insted of two
  CharlieBackend.Business/Services/AccountService.cs
Labels: good first issue

#387 Bug/Course IsActive property must be true after update
  CharlieBackend.Api.UnitTes/CourseServiceTest.cs
  CharlieBackend.Business/Services/CourseService.cs
  CharlieBackend.Data/Repositories/Impl/CourseRepository.cs
  CharlieBackend.Data/Repositories/Impl/Interfaces/ICourseRepository.cs
Labels: bug

#362 Refactored Services and Util in AdminPanel
  CharlieBackend.AdminPanel/Controllers/AccountController.cs
  CharlieBackend.AdminPanel/Controllers/MentorsController.cs
  CharlieBackend.AdminPanel/Controllers/UsersController.cs
  CharlieBackend.AdminPanel/Services/CourseService.cs
  CharlieBackend.AdminPanel/Services/MentorService.cs
  CharlieBackend.AdminPanel/Services/StudentGroupService.cs
  CharlieBackend.AdminPanel/Services/StudentService.cs
  CharlieBackend.AdminPanel/Services/ThemeService.cs
  CharlieBackend.AdminPanel/Startup.cs
  CharlieBackend.AdminPanel/Utils/ApiUtil.cs
  CharlieBackend.AdminPanel/Utils/HttpUtil.cs
  CharlieBackend.AdminPanel/Utils/Interfaces/IApiUtil.cs
  CharlieBackend.AdminPanel/Utils/Interfaces/IHttpUtil.cs
Labels: enhancement

#404 Unit tests for EventOccurenceStorageParser (transferred from old branch)
  CharlieBackend.Api.UnitTes/EventOcurranceStorageParserTests.cs
Labels: development

#411 Fixed problem in Dublicate method
  CharlieBackend.Business/Services/MentorService.cs
  CharlieBackend.Business/Services/StudentService.cs
Labels: bug

#413 Unit tests for method GetEvents in ScheduledEvent..
  CharlieBackend.Api.UnitTes/ScheduledEventHandlerRelativeMonthlyTests.cs
Labels: development

#425 Refactor class TestBase
  CharlieBackend.Api.UnitTes/AccountServiceTests.cs
  CharlieBackend.Api.UnitTes/CourseServiceTest.cs
  CharlieBackend.Api.UnitTes/DashboardServiceTest.cs
  CharlieBackend.Api.UnitTes/LessonServiceTests.cs
  CharlieBackend.Api.UnitTes/MentorServiceTests.cs
  CharlieBackend.Api.UnitTes/RepositoriesTests/DashboardRepositoryTest.cs
  CharlieBackend.Api.UnitTes/SecretaryServiceTests.cs
  CharlieBackend.Api.UnitTes/StudentGroupServiceTest.cs
  CharlieBackend.Api.UnitTes/StudentServiceTests.cs
  CharlieBackend.Api.UnitTes/TestBase.cs
Labels: enhancement

#396 Creating validators for account(fluent validation)
  CharlieBackend.Api/CharlieBackend.Api.csproj
  CharlieBackend.Api/Controllers/AccountsController.cs
  CharlieBackend.Api/Startup.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/AccountDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/AuthenticationDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/ChangeCurrentPasswordDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/CreateAccountDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/ForgotPasswordDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/ResetPasswordDtoValidator.cs
  CharlieBackend.Core/CharlieBackend.Core.csproj
  CharlieBackend.Core/DTO/Account/AccountDto.cs
  CharlieBackend.Core/DTO/Account/AuthenticationDto.cs
  CharlieBackend.Core/DTO/Account/ChangeCurrentPasswordDto.cs
  CharlieBackend.Core/DTO/Account/CreateAccountDto.cs
  CharlieBackend.Core/DTO/Account/ForgotPasswordDto.cs
  CharlieBackend.Core/DTO/Account/ResetPasswordDto.cs
  CharlieBackend.Root/CompositionRoot.cs
Labels: development, enhancement

#406 Unit Tests for CreateScheduleAsync in Schedule Service (transferred from old branch)
  CharlieBackend.Api.UnitTes/ScheduleServiceTests.cs
Labels: development, enhancement
