Repository ita-social-projects/WhatBackend, pull requests merged in 2022-04, with the labels that each got.

#840 Add functionality to the button update scheduled event in WHAT Panel
  CharlieBackend.Panel/ApplicationSettings.cs
  CharlieBackend.Panel/Controllers/EventOccurrenceController.cs
  CharlieBackend.Panel/HtmlHelpers/CalendarHelper.cs
  CharlieBackend.Panel/Models/Calendar/CalendarScheduledEventModel.cs
  CharlieBackend.Panel/Services/Interfaces/IScheduleService.cs
  CharlieBackend.Panel/Services/ScheduleService.cs
  CharlieBackend.Panel/Views/Calendar/Index.cshtml
  CharlieBackend.Panel/Views/EventOccurrence/UpdateSingleEvent.cshtml
  CharlieBackend.Panel/appsettings.json
Labels: development

#843 #834 fix bag time in Event
  CharlieBackend.Business/Services/ScheduleServiceFolder/Helpers/SchedulesUpdater.cs
Labels: bug

#846 Enhancement edit pages
  CharlieBackend.Business/Services/StudentService.cs
  CharlieBackend.Panel/ApplicationSettings.cs
  CharlieBackend.Panel/Controllers/EventOccurrenceController.cs
  CharlieBackend.Panel/Models/EventOccurrence/EventOccurrenceEditViewModel.cs
  CharlieBackend.Panel/Models/Mapping/ViewModelMapping.cs
  CharlieBackend.Panel/Models/Mentor/MentorEditViewModel.cs
  CharlieBackend.Panel/Models/ScheduledEvent/ScheduledEventEditViewModel.cs
  CharlieBackend.Panel/Models/Students/StudentEditViewModel.cs
  CharlieBackend.Panel/Services/Interfaces/IScheduleService.cs
  CharlieBackend.Panel/Services/MentorService.cs
  CharlieBackend.Panel/Services/ScheduleService.cs
  CharlieBackend.Panel/Services/StudentService.cs
  CharlieBackend.Panel/Views/EventOccurrence/UpdateEventOccurrence.cshtml
  CharlieBackend.Panel/Views/EventOccurrence/UpdateSingleEvent.cshtml
  CharlieBackend.Panel/Views/Mentors/UpdateMentor.cshtml
  CharlieBackend.Panel/Views/Students/UpdateStudent.cshtml
  CharlieBackend.Panel/appsettings.json
Labels: enhancement

#849 Remove Event Occurrences page
  CharlieBackend.Panel/Controllers/EventOccurrenceController.cs
  CharlieBackend.Panel/Views/Calendar/Index.cshtml
  CharlieBackend.Panel/Views/EventOccurrence/AllEventOccurrences.cshtml
  CharlieBackend.Panel/Views/Shared/_Layout.cshtml
Labels: enhancement
