Repository ita-social-projects/WhatBackend, pull requests merged in 2022-05, with the labels that each got.

#857 441 Add single event
  CharlieBackend.Api.UnitTes/EventServiceTest.cs
  CharlieBackend.Api/Controllers/EventsController.cs
  CharlieBackend.Business/Services/Interfaces/IEventsService.cs
  CharlieBackend.Business/Services/ScheduleServiceFolder/EventsService.cs
  CharlieBackend.Business/Services/ScheduleServiceFolder/Helpers/ISchedulesEventsDbEntityVerifier.cs
  CharlieBackend.Business/Services/ScheduleServiceFolder/Helpers/SchedulesEventsDbEntityVerifier.cs
  CharlieBackend.Core/DTO/Event/CreateSingleEventDTO.cs
  CharlieBackend.Core/DTO/Event/SingleEventDTO.cs
  CharlieBackend.Core/Entities/ScheduledEvent.cs
  CharlieBackend.Core/Mapping/ModelMappingProfile.cs
  scripts/10_update_data_for_scheduledevents.sql
Labels: development

#865 852 fluent validators enchancments
  CharlieBackend.Api.UnitTes/ValidatorsTests/AccountDtoValidatorsTests/AuthenticationDtoValidatorTests.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/AccountDtoValidatorsTests/ChangeCurrentPasswordDtoValidatorTests.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/AccountDtoValidatorsTests/CreateAccountDtoValidatorTests.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/AccountDtoValidatorsTests/ForgotPasswordDtoValidatorTests.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/AccountDtoValidatorsTests/ResetPasswordDtoValidatorTests.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/MentorDtoValidatorsTests/UpdateMentorDtoValidatorTests.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/PatternForCreateScheduleDTOValidatorTests.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/ScheduleDTOValidatorsTests/ContextForCreateScheduleDTOValidatorTests.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/ScheduleDTOValidatorsTests/CreateScheduleDtoValidatorTests.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/ScheduleDTOValidatorsTests/EventUpdateRangeDTOValidatorTests.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/ScheduleDTOValidatorsTests/OccurenceRangeValidatorTests.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/ScheduleDTOValidatorsTests/PatternForCreateScheduleDTOValidatorTests.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/ScheduleDTOValidatorsTests/ScheduleTestValidationConstants.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/ScheduleDTOValidatorsTests/ScheduledEventFilterRequestDTOValidatorTests.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/ScheduleDTOValidatorsTests/UpdateScheduleDtoValidatorTests.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/ScheduledEventFilterRequestDTOValidatorTests.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/SecretaryDtoValidatorsTests/UpdateSecretaryDtoValidatorTests.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/StudentDTOValidatorsTests/UpdateStudentDtoValidatorTests.cs
  CharlieBackend.Api.UnitTes/ValidatorsTests/TestValidationConstants.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/AccountRoleDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/AuthenticationDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/ChangeCurrentPasswordDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/CreateAccountDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/ForgotPasswordDtoValidator.cs
  CharlieBackend.Api/Validators/AccountDTOValidators/ResetPasswordDtoValidator.cs
  CharlieBackend.Api/Validators/MentorDTOValidators/UpdateMentorDtoValidator.cs
  CharlieBackend.Api/Validators/ScheduleDTOValidators/CreateScheduleDTO/ContextForCreateScheduleDTOValidators.cs
  CharlieBackend.Api/Validators/ScheduleDTOValidators/CreateScheduleDTO/CreateScheduleDtoValidator.cs
  CharlieBackend.Api/Validators/ScheduleDTOValidators/CreateScheduleDTO/OccurenceRangeValidator.cs
  CharlieBackend.Api/Validators/ScheduleDTOValidators/CreateScheduleDTO/PatternForCreateScheduleDTOValidator.cs
  CharlieBackend.Api/Validators/ScheduleDTOValidators/EventUpdateRangeDTOValidator.cs
  CharlieBackend.Api/Validators/ScheduleDTOValidators/ScheduledEventFilterRequestDTOValidator.cs
  CharlieBackend.Api/Validators/ScheduleDTOValidators/UpdateScheduleDtoValidator.cs
  CharlieBackend.Api/Validators/ScheduleDTOValidators/UpdateScheduledEventDtoValidator.cs
  CharlieBackend.Api/Validators/SecretaryDTOValidators/UpdateSecretaryDtoValidator.cs
  CharlieBackend.Api/Validators/StudentDTOValidators/UpdateStudentDtoValidator.cs
  CharlieBackend.Business/Helpers/ValidationConstants.cs
Labels: enhancement

#876 Add the ability to create a single event in Panel
  CharlieBackend.Api.UnitTes/ScheduleServiceTests.cs
  CharlieBackend.Core/DTO/Schedule/ScheduledEventDTO.cs
  CharlieBackend.Data/Configurations/ScheduledEventEntityConfiguration.cs
  CharlieBackend.Data/Repositories/Impl/ScheduledEventRepository.cs
  CharlieBackend.Panel/ApplicationSettings.cs
  CharlieBackend.Panel/Controllers/EventOccurrenceController.cs
  CharlieBackend.Panel/HtmlHelpers/CalendarHelper.cs
  CharlieBackend.Panel/Models/Calendar/CalendarScheduledEventModel.cs
  CharlieBackend.Panel/Services/Interfaces/IScheduleService.cs
  CharlieBackend.Panel/Services/ScheduleService.cs
  CharlieBackend.Panel/Views/Calendar/Index.cshtml
  CharlieBackend.Panel/Views/EventOccurrence/AddSingleEvent.cshtml
  CharlieBackend.Panel/appsettings.json
Labels: enhancement

#871 Add opportunity export data in panel
  CharlieBackend.Panel/ApplicationSettings.cs
  CharlieBackend.Panel/Controllers/ExportController.cs
  CharlieBackend.Panel/Extensions/Extensions.cs
  CharlieBackend.Panel/Extensions/FileResponseControllerExtension.cs
  CharlieBackend.Panel/Models/Export/ExportByCourseAndStudentGroupModel.cs
  CharlieBackend.Panel/Models/Export/ExportByDateRangeModel.cs
  CharlieBackend.Panel/Models/Export/ExportFileFormat.cs
  CharlieBackend.Panel/Services/ExportService.cs
  CharlieBackend.Panel/Services/Interfaces/IExportService.cs
  CharlieBackend.Panel/Utils/ApiUtil.cs
  CharlieBackend.Panel/Utils/Interfaces/IBinaryResultApiUtil.cs
  CharlieBackend.Panel/Views/Classbook/Index.cshtml
  CharlieBackend.Panel/Views/Shared/_Layout.cshtml
  CharlieBackend.Panel/appsettings.json
  CharlieBackend.Panel/wwwroot/css/site.css
  CharlieBackend.Panel/wwwroot/js/site.js
Labels: development

#898 Delete single event
  CharlieBackend.Panel/ApplicationSettings.cs
  CharlieBackend.Panel/Controllers/EventOccurrenceController.cs
  CharlieBackend.Panel/Services/Interfaces/IScheduleService.cs
  CharlieBackend.Panel/Services/ScheduleService.cs
  CharlieBackend.Panel/Views/Calendar/Index.cshtml
  CharlieBackend.Panel/appsettings.json
  CharlieBackend.Panel/wwwroot/js/calendar.js
Labels: enhancement

#883 export documentation
  CharlieBackend.Panel/Extensions/FileResponseControllerExtension.cs
  CharlieBackend.Panel/Models/Export/ExportFileFormat.cs
  CharlieBackend.Panel/Utils/Interfaces/IBinaryResultApiUtil.cs
Labels: documentation

#896 Tests/887 Add tests for studentGroupService
  CharlieBackend.Api.UnitTes/StudentGroupServiceTest.cs
  CharlieBackend.Business/Services/Interfaces/IStudentGroupService.cs
  CharlieBackend.Business/Services/StudentGroupService.cs
Labels: tests

#885 Tests/881, Add tests for secretary service
  CharlieBackend.Api.UnitTes/SecretaryServiceTests.cs
  CharlieBackend.Business/Services/SecretaryService.cs
  CharlieBackend.Core/DTO/Secretary/UpdateSecretaryDto.cs
Labels: tests
